// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protos/message.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace GrpcService {
  /// <summary>
  /// The message service definition
  /// </summary>
  public static partial class MessageService
  {
    static readonly string __ServiceName = "MessageService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::GrpcService.CreateMessageRequest> __Marshaller_CreateMessageRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::GrpcService.CreateMessageRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Google.Protobuf.WellKnownTypes.Empty> __Marshaller_google_protobuf_Empty = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Google.Protobuf.WellKnownTypes.Empty.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::GrpcService.GetMessagesBetweenUsersRequest> __Marshaller_GetMessagesBetweenUsersRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::GrpcService.GetMessagesBetweenUsersRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::GrpcService.MessageListResponse> __Marshaller_MessageListResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::GrpcService.MessageListResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::GrpcService.GetMessagesForGroupRequest> __Marshaller_GetMessagesForGroupRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::GrpcService.GetMessagesForGroupRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::GrpcService.UpdateMessageContentRequest> __Marshaller_UpdateMessageContentRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::GrpcService.UpdateMessageContentRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::GrpcService.DeleteMessageRequest> __Marshaller_DeleteMessageRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::GrpcService.DeleteMessageRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::GrpcService.SoftDeleteMessageRequest> __Marshaller_SoftDeleteMessageRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::GrpcService.SoftDeleteMessageRequest.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::GrpcService.CreateMessageRequest, global::Google.Protobuf.WellKnownTypes.Empty> __Method_CreateMessage = new grpc::Method<global::GrpcService.CreateMessageRequest, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CreateMessage",
        __Marshaller_CreateMessageRequest,
        __Marshaller_google_protobuf_Empty);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::GrpcService.GetMessagesBetweenUsersRequest, global::GrpcService.MessageListResponse> __Method_GetMessagesBetweenUsers = new grpc::Method<global::GrpcService.GetMessagesBetweenUsersRequest, global::GrpcService.MessageListResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetMessagesBetweenUsers",
        __Marshaller_GetMessagesBetweenUsersRequest,
        __Marshaller_MessageListResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::GrpcService.GetMessagesForGroupRequest, global::GrpcService.MessageListResponse> __Method_GetMessagesForGroup = new grpc::Method<global::GrpcService.GetMessagesForGroupRequest, global::GrpcService.MessageListResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetMessagesForGroup",
        __Marshaller_GetMessagesForGroupRequest,
        __Marshaller_MessageListResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::GrpcService.UpdateMessageContentRequest, global::Google.Protobuf.WellKnownTypes.Empty> __Method_UpdateMessageContent = new grpc::Method<global::GrpcService.UpdateMessageContentRequest, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "UpdateMessageContent",
        __Marshaller_UpdateMessageContentRequest,
        __Marshaller_google_protobuf_Empty);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::GrpcService.DeleteMessageRequest, global::Google.Protobuf.WellKnownTypes.Empty> __Method_DeleteMessage = new grpc::Method<global::GrpcService.DeleteMessageRequest, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "DeleteMessage",
        __Marshaller_DeleteMessageRequest,
        __Marshaller_google_protobuf_Empty);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::GrpcService.SoftDeleteMessageRequest, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SoftDeleteMessage = new grpc::Method<global::GrpcService.SoftDeleteMessageRequest, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SoftDeleteMessage",
        __Marshaller_SoftDeleteMessageRequest,
        __Marshaller_google_protobuf_Empty);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::GrpcService.MessageReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of MessageService</summary>
    [grpc::BindServiceMethod(typeof(MessageService), "BindService")]
    public abstract partial class MessageServiceBase
    {
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> CreateMessage(global::GrpcService.CreateMessageRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::GrpcService.MessageListResponse> GetMessagesBetweenUsers(global::GrpcService.GetMessagesBetweenUsersRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::GrpcService.MessageListResponse> GetMessagesForGroup(global::GrpcService.GetMessagesForGroupRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> UpdateMessageContent(global::GrpcService.UpdateMessageContentRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> DeleteMessage(global::GrpcService.DeleteMessageRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> SoftDeleteMessage(global::GrpcService.SoftDeleteMessageRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(MessageServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_CreateMessage, serviceImpl.CreateMessage)
          .AddMethod(__Method_GetMessagesBetweenUsers, serviceImpl.GetMessagesBetweenUsers)
          .AddMethod(__Method_GetMessagesForGroup, serviceImpl.GetMessagesForGroup)
          .AddMethod(__Method_UpdateMessageContent, serviceImpl.UpdateMessageContent)
          .AddMethod(__Method_DeleteMessage, serviceImpl.DeleteMessage)
          .AddMethod(__Method_SoftDeleteMessage, serviceImpl.SoftDeleteMessage).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, MessageServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_CreateMessage, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::GrpcService.CreateMessageRequest, global::Google.Protobuf.WellKnownTypes.Empty>(serviceImpl.CreateMessage));
      serviceBinder.AddMethod(__Method_GetMessagesBetweenUsers, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::GrpcService.GetMessagesBetweenUsersRequest, global::GrpcService.MessageListResponse>(serviceImpl.GetMessagesBetweenUsers));
      serviceBinder.AddMethod(__Method_GetMessagesForGroup, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::GrpcService.GetMessagesForGroupRequest, global::GrpcService.MessageListResponse>(serviceImpl.GetMessagesForGroup));
      serviceBinder.AddMethod(__Method_UpdateMessageContent, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::GrpcService.UpdateMessageContentRequest, global::Google.Protobuf.WellKnownTypes.Empty>(serviceImpl.UpdateMessageContent));
      serviceBinder.AddMethod(__Method_DeleteMessage, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::GrpcService.DeleteMessageRequest, global::Google.Protobuf.WellKnownTypes.Empty>(serviceImpl.DeleteMessage));
      serviceBinder.AddMethod(__Method_SoftDeleteMessage, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::GrpcService.SoftDeleteMessageRequest, global::Google.Protobuf.WellKnownTypes.Empty>(serviceImpl.SoftDeleteMessage));
    }

  }
}
#endregion
